### ISSUE TITLE
Add a runexports

### ISSUE THREAD

**Issue by wolfv** [conda-forge/log4cxx-feedstock#5]
Currently log4cxx doesn't have a run_exports, but it's needed since we're distributing a shared library.

**Comment by beckermr** [comment]
Yes and it appears the .so name is changing. 

<img width="562" alt="Screen Shot 2020-11-20 at 4 16 46 PM" src="https://user-images.githubusercontent.com/5296416/99855176-d1f57c80-2b4b-11eb-97cb-a62dd65a690d.png">
