### ISSUE TITLE
run_exports still wrong

### ISSUE THREAD

**Issue by wolfv** [conda-forge/log4cxx-feedstock#7]
I checked the run_exports data on OS X and it just exports `log4cxx` without any version. 

```
{"weak": ["log4cxx"]}
```

Not sure why, since the run_exports command is `pin_compatible(..., max_pin='x.x.x')`.

Although: shouldn't that be `pin_subpackage`? cc @beckermr

**Comment by beckermr** [comment]
Ack. Let's try the subpackage one.

**Comment by beckermr** [comment]
fixed!

**Comment by wolfv** [comment]
sweet, thanks!
